name: Accessibility Check

on:
  pull_request:
    branches:
      - master

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome

      - name: Run Accessibility Check
        uses: mariaparfenyuk/github-action-accessibility-check@v1
        with:
          url: 'https://wikipedia.org'